kind: Service
apiVersion: v1
metadata:
  name: parcial
spec:
  selector:
    app: parcial
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: parcial
  name: parcial
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: parcial
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: parcial
        tier: frontend
        track: stable
    spec:
      containers:
      - name: parcial
        image: "largnaster/parcial:13"
        env:
          - name: MONGO_URL
            value: "mongodb://dbparcial:27017/test"
        ports:
            - name: http
              containerPort: 3000
        imagePullPolicy: Always
        resources: 
            requests:
                cpu: "100m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30